Models/ErrorViewModel.cs
using System;

namespace ImaginarySoftwareCompany.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Software.cs
using ImaginarySoftwareCompany.Helpers;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ImaginarySoftwareCompany.Models
{
    public class Software
    {
        public string Name { get; set; }
        public Version Version { get; set; }
    }
}

Models/VersionManager.cs
using ImaginarySoftwareCompany.Helpers;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ImaginarySoftwareCompany.Models
{
    public class VersionManager
    {
        public IEnumerable<Software> SoftwareVersions { get; set; }

        [Version]
        public string Version { get; set; }
    }
}

Controllers/HomeController.cs
using ImaginarySoftwareCompany.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;

namespace ImaginarySoftwareCompany.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View("SoftwareSearch");
        }
    }
}

Controllers/SoftwareResultsController.cs
using ImaginarySoftwareCompany.Helpers;
using ImaginarySoftwareCompany.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ImaginarySoftwareCompany.Controllers
{
    public class SoftwareResultsController : Controller
    {
        [HttpPost]
        public IActionResult RetrieveNewerSoftwareVersions(VersionManager currentSoftware)
        {
            if (ModelState.IsValid)
            {
                //Get list of results
                VersionManager resultManager = new VersionManager();
                resultManager.SoftwareVersions = SoftwareManager.GetSuccessiveSoftwareVersions(currentSoftware);
                resultManager.Version = currentSoftware.Version;
                return View("~/Views/Home/SoftwareSearch.cshtml", resultManager);
            }
            else
            {
                return View("~/Views/Home/SoftwareSearch.cshtml");
            }

        }
    }
}

Views/Home/SoftwareSearch.cshtml
@model ImaginarySoftwareCompany.Models.VersionManager
@{
    ViewData["Title"] = "Software Lookup";
}
<div class="page-header">
    <h3>Software Product Lookup</h3>
</div>

<form asp-action="RetrieveNewerSoftwareVersions" asp-controller="SoftwareResults" method="post" class="formLayout">
    <div class="form-group">
        <label asp-for="Version">Version Number: </label>
        <input asp-for="Version" class="form-control" placeholder="[major version].[minor version].[patch]" />
    </div>

    <button type="submit" class="btn btn-primary" value="Submit">Find Succeeding Software Versions</button>
</form>

<div asp-validation-summary="All"></div>

<div id="SuccessiveSoftwareVersions">
    @if (Model?.SoftwareVersions != null)
    {
        @await Html.PartialAsync("VersionResults", Model.SoftwareVersions);
    }

</div>

Views/Shared/VersionResults.cshtml
@model IEnumerable<ImaginarySoftwareCompany.Models.Software>

@if (Model != null)
{
    <table class="table table-striped table-hover">
        <thead class="thead-dark">
            <tr>
                <th>Software Name</th>
                <th>Software Version</th>
            </tr>
        </thead>
        <tbody>
            @{
                if (Model.Count() < 1)
                {
                    <tr>
                        <td>There weren't any versions greater than version provided</td>
                        <td>-----------------------------------------</td>
                    </tr>
                }
                else
                {
                    foreach (Software preceedingVersion in Model)
                    {
                        <tr>
                            <td>@preceedingVersion.Name</td>
                            <td>@preceedingVersion.Version</td>
                        </tr>
                    }
                }
            }


        </tbody>
    </table>
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ImaginarySoftwareCompany</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">ImaginarySoftwareCompany</a>
            </div>
        </div>
    </nav>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - ImaginarySoftwareCompany</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>